import { ReadItem } from '../lib/types';

export const mockReads: ReadItem[] = [
  { 
    id: 1, 
    type: "Manga", 
    coverImage: "/pictures/image.png",
    availableImages: ["/pictures/image.png", "/pictures/image2.png"], 
    title: "A Regressor's Tale of Cultivation", 
    altTitle: "회귀수선전",
    desc: "It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation.", 
    published: "2023-01-01",
    updated: "2025-02-01",
    lastRead: "2023-09-12", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Great", 
    chapter: 12, 
    comicChapter: 150, 
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    category: [
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Misunderstanding/s", 
      "Nobility/Aristocracy", 
      "Based on a Web Novel"
    ],
    source: ["Asura Scans"],
    sourceIcon: ["/icons/asura-icon.webp"],
    relations: [4, 7, 12] 
  },
  { 
    id: 2, 
    type: "Manhua", 
    coverImage: "/pictures/image2.png",
    availableImages: ["/pictures/image2.png", "/pictures/image3.png"], 
    title: "The Regressed Mercenary Has a Plan", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc: "Cecil Perdium, the Mercenary King, was killed in battle before he could avenge his family. Suddenly waking up as his teenage self.", 
    published: "2024-01-10",
    updated: "2025-01-20",
    lastRead: "2024-07-16", 
    status: "Dropped", 
    comicStatus: "Ongoing",
    rating: "Absolute Cinema", 
    chapter: 4,
    comicChapter: 60,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "Webtoon", 
      "Full Color", 
      "21st Century", 
      "Strong Male Lead", 
      "Handsome Male Lead", 
      "Male Protagonist", 
      "Based on a Web Novel", 
      "Age Gap", 
      "Revenge"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [5, 8, 10, 13]
  },
  { 
    id: 3, 
    type: "Manhwa",  
    coverImage: "/pictures/image3.png",
    availableImages: ["/pictures/image3.png", "/pictures/image4.png"], 
    title: "The Knight Who Only Lives Today", 
    altTitle: "Eternally Regressing Knight",
    desc: "Is dying repeatedly a blessing? Enkrid's life-long dream of becoming a knight looked to be forever out of reach.", 
    published: "2023-05-15",
    updated: "2025-02-05",
    lastRead: "2023-06-19", 
    status: "On Hold", 
    comicStatus: "Ongoing",
    rating: "Bad", 
    chapter: 8,
    comicChapter: 45,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "European Ambience", 
      "Nobility/Aristocracy", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Unrequited Love"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [6, 9, 11]
  },
  { 
    id: 4, 
    type: "Manga", 
    coverImage: "/pictures/image4.png",
    availableImages: ["/pictures/image4.png", "/pictures/image5.png"], 
    title: "A Regressor's Tale of Cultivation: The Beginning", 
    altTitle: "회귀수선전",
    desc: "A Korean take on the Chinese Xianxia genre. MC survives through repeated regressions to find a path to immortality.", 
    published: "2023-01-01",
    updated: "2025-01-01",
    lastRead: "2025-04-12", 
    status: "Completed", 
    comicStatus: "Finished",
    rating: "Good", 
    chapter: 12,
    comicChapter: 12, 
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    category: [
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Misunderstanding/s", 
      "Nobility/Aristocracy", 
      "Collection of Stories"
    ],
    source: ["Asura Scans"],
    sourceIcon: ["/icons/asura-icon.webp"],
    relations: [1, 7, 12]
  },
  { 
    id: 5, 
    type: "Manhua", 
    coverImage: "/pictures/image2.png",
    availableImages: ["/pictures/image2.png", "/pictures/image.png"], 
    title: "The Regressed Mercenary Has a Plan (Season 2)", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc: "Cecil Perdium, the Mercenary King, uses his future knowledge to rebuild his family's legacy.", 
    published: "2024-02-14",
    updated: "2025-06-01",
    lastRead: "2025-6-27", 
    status: "Dropped", 
    comicStatus: "Ongoing",
    rating: "Awesome", 
    chapter: 4,
    comicChapter: 88,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "Webtoon", 
      "Full Color", 
      "21st Century", 
      "Strong Male Lead", 
      "Handsome Male Lead", 
      "Male Protagonist", 
      "Based on a Web Novel", 
      "High School Student/s", 
      "Love Triangle/s"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [2, 8, 10, 13]
  },
  { 
    id: 6, 
    type: "Manhwa", 
    coverImage: "/pictures/image.png",
    availableImages: ["/pictures/image.png", "/pictures/image3.png"], 
    title: "The Knight Who Only Lives Today: Reborn", 
    altTitle: "Eternally Regressing Knight",
    desc: "Enkrid finds himself in a time loop, dying every day and waking up at the start to try again.", 
    published: "2023-04-01",
    updated: "2023-04-18",
    lastRead: "2023-04-18", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Garbage", 
    chapter: 8,
    comicChapter: 100,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "European Ambience", 
      "Nobility/Aristocracy", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Childhood Friend/s"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [3, 9, 11]
  },
  { 
    id: 7, 
    type: "Manga", 
    coverImage: "/pictures/image3.png",
    availableImages: ["/pictures/image3.png", "/pictures/image2.png"], 
    title: "A Regressor's Tale of Cultivation (Side Story)", 
    altTitle: "회귀수선전",
    desc: "Struggling through the harsh world of cultivation without innate talent.", 
    published: "2023-01-01",
    updated: "2025-08-01",
    lastRead: "2025-08-01", 
    status: "On Hold", 
    comicStatus: "Ongoing",
    rating: "Good", 
    chapter: 12,
    comicChapter: 200,
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    category: [
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Misunderstanding/s", 
      "Nobility/Aristocracy", 
      "University/Post-Secondary Student/s"
    ],
    source: ["Asura Scans"],
    sourceIcon: ["/icons/asura-icon.webp"],
    relations: [1, 4, 12]
  },
  { 
    id: 8, 
    type: "Manhua", 
    coverImage: "/pictures/image.png",
    availableImages: ["/pictures/image.png", "/pictures/image4.png"], 
    title: "The Regressed Mercenary: Origins", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc: "Cecil's journey to becoming the strongest mercenary through regression.", 
    published: "2024-02-14",
    updated: "2025-09-10",
    lastRead: "2025-09-11", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Great", 
    chapter: 4,
    comicChapter: 110,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "Webtoon", 
      "Full Color", 
      "21st Century", 
      "Strong Male Lead", 
      "Handsome Male Lead", 
      "Male Protagonist", 
      "Based on a Web Novel", 
      "Childhood Friend/s", 
      "High School"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [2, 5, 10, 13]
  },
  { 
    id: 9, 
    type: "Manhwa", 
    coverImage: "/pictures/image4.png",
    availableImages: ["/pictures/image4.png", "/pictures/image5.png"], 
    title: "The Knight Who Only Lives Today (Finale)", 
    altTitle: "Eternally Regressing Knight",
    desc: "Final stand of the knight Enkrid as he reaches the end of his cycle.", 
    published: "2023-04-01",
    updated: "2025-09-20",
    lastRead: "2025-9-21", 
    status: "Completed", 
    comicStatus: "Finished",
    rating: "Garbage", 
    chapter: 8,
    comicChapter: 8,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "European Ambience", 
      "Nobility/Aristocracy", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Unrequited Love"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [3, 6, 11]
  },
  { 
    id: 10, 
    type: "Manhua", 
    coverImage: "/pictures/image2.png",
    availableImages: ["/pictures/image2.png", "/pictures/image3.png"], 
    title: "The Regressed Mercenary: Final War", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc: "High stakes action as Cecil's plan enters the final phase.", 
    published: "2024-02-14",
    updated: "2025-09-22",
    lastRead: "2025-09-22", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Absolute Cinema", 
    chapter: 4,
    comicChapter: 125,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "Webtoon", 
      "Full Color", 
      "21st Century", 
      "Strong Male Lead", 
      "Handsome Male Lead", 
      "Male Protagonist", 
      "Based on a Web Novel", 
      "Age Gap", 
      "Glasses-Wearing Male Lead"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [2, 5, 8, 13]
  },
  { 
    id: 11, 
    type: "Manhwa", 
    coverImage: "/pictures/image3.png",
    availableImages: ["/pictures/image3.png", "/pictures/image.png"], 
    title: "The Knight Who Only Lives Today: Gaiden", 
    altTitle: "Eternally Regressing Knight",
    desc: "Enkrid faces a new challenger in the latest loop.", 
    published: "2023-04-01",
    updated: "2025-09-23",
    lastRead: "2025-09-23", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Bad", 
    chapter: 8,
    comicChapter: 115,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "European Ambience", 
      "Nobility/Aristocracy", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Older Male Younger Female"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [3, 6, 9]
  },
  { 
    id: 12, 
    type: "Manga", 
    coverImage: "/pictures/image4.png",
    availableImages: ["/pictures/image4.png", "/pictures/image2.png"], 
    title: "A Regressor's Tale: New Arc", 
    altTitle: "회귀수선전",
    desc: "New arc begins for the regressor.", 
    published: "2023-01-01",
    updated: "2025-09-24",
    lastRead: "2025-09-24", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Good", 
    chapter: 12,
    comicChapter: 215,
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    category: [
      "Full Color", 
      "Webtoon", 
      "Based on a Novel", 
      "Magic", 
      "Strong Male Lead", 
      "Male Protagonist", 
      "Misunderstanding/s", 
      "Nobility/Aristocracy", 
      "Web Comic"
    ],
    source: ["Asura Scans"],
    sourceIcon: ["/icons/asura-icon.webp"],
    relations: [1, 4, 7]
  },
  { 
    id: 13, 
    type: "Manhua", 
    coverImage: "/pictures/image2.png",
    availableImages: ["/pictures/image2.png", "/pictures/image3.png"], 
    title: "The Regressed Mercenary: Epilogue", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc: "Cecil's power growth continues to shock the world.", 
    published: "2024-02-14",
    updated: "2025-09-25",
    lastRead: "2025-09-25", 
    status: "Ongoing", 
    comicStatus: "Publishing",
    rating: "Awesome", 
    chapter: 4,
    comicChapter: 130,
    tags: ["Action", "Fantasy", "Adventure"],
    category: [
      "Webtoon", 
      "Full Color", 
      "21st Century", 
      "Strong Male Lead", 
      "Handsome Male Lead", 
      "Male Protagonist", 
      "Based on a Web Novel", 
      "Older Female Younger Male", 
      "Strong Female Lead"
    ],
    source: ["Webtoon", "Asura Scans"],
    sourceIcon: ["/icons/webtoon-icon.png", "/icons/asura-icon.webp"],
    relations: [2, 5, 8, 10]
  },
];