import { ReadItem } from '../app/user/home/components/types';

export const mockReads: ReadItem[] = [
  { 
    id: 1, 
    type: "manga", 
    imageUrl: "/pictures/image.png", 
    title: "A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation A Regressor's Tale of Cultivation", 
    altTitle: "회귀수선전",
    desc:"It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life. It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life. It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life. It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life. It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life. It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life.", 
    lastRead: "2023-09-12", 
    status: "Ongoing", 
    rating: "Good", 
    chapter: "Chapter 12",
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    source: ["Asura Scans"]
  },
  { 
    id: 2, 
    type: "manhua", 
    imageUrl: "/pictures/image2.png", 
    title: "The Regressed Mercenary Has a Plan", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc:"Cecil Perdium, the Mercenary King, was killed in battle before he could avenge his family. Suddenly waking up as his teenage self, Cecil must work to both overcome his poor reputation and build up his strength to save his family. Can Cecil become the mighty warrior he once was and avert his family's fate?", 
    lastRead: "2024-07-16", 
    status: "Dropped", 
    rating: "Good", 
    chapter: "Chapter 4",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 3, 
    type: "manhwa",  
    imageUrl: "/pictures/image3.png", 
    title: "The Knight Who Only Lives Today", 
    altTitle: "Eternally Regressing Knight",
    desc:"Is dying repeatedly a blessing? Enkrid's life-long dream of becoming a knight looked to be forever out of reach, until one day he died... and woke up at the beginning of that same day! Now that he has unlimited chances to train and engage in mortal combat, just how far can he go?", 
    lastRead: "2023-6-19", 
    status: "On Hold", 
    rating: "Bad", 
    chapter: "Chapter 8",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 4, 
    type: "manga", 
    imageUrl: "/pictures/image4.png", 
    title: "A Regressor's Tale of Cultivation", 
    altTitle: "회귀수선전",
    desc:"It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life.", 
    lastRead: "2025-04-12", 
    status: "Completed", 
    rating: "Good", 
    chapter: "Chapter 12",
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    source: ["Asura Scans"]
  },
  { 
    id: 5, 
    type: "manhua", 
    imageUrl: "/pictures/image2.png", 
    title: "The Regressed Mercenary Has a Plan", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc:"Cecil Perdium, the Mercenary King, was killed in battle before he could avenge his family. Suddenly waking up as his teenage self, Cecil must work to both overcome his poor reputation and build up his strength to save his family. Can Cecil become the mighty warrior he once was and avert his family's fate?", 
    lastRead: "2025-6-27", 
    status: "Dropped", 
    rating: "Mid", 
    chapter: "Chapter 4",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 6, 
    type: "manhwa", 
    imageUrl: "/pictures/image.png", 
    title: "The Knight Who Only Lives Today", 
    altTitle: "Eternally Regressing Knight",
    desc:"Is dying repeatedly a blessing? Enkrid's life-long dream of becoming a knight looked to be forever out of reach, until one day he died... and woke up at the beginning of that same day! Now that he has unlimited chances to train and engage in mortal combat, just how far can he go?", 
    lastRead: "2023-04-18", 
    status: "Ongoing", 
    rating: "Mid", 
    chapter: "Chapter 8",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 7, 
    type: "manga", 
    imageUrl: "/pictures/image3.png", 
    title: "A Regressor's Tale of Cultivation", 
    altTitle: "회귀수선전",
    desc:"It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life.", 
    lastRead: "2025-08-01", 
    status: "On Hold", 
    rating: "Good", 
    chapter: "Chapter 12",
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    source: ["Asura Scans"]
  },
  { 
    id: 8, 
    type: "manhua", 
    imageUrl: "/pictures/image.png", 
    title: "The Regressed Mercenary Has a Plan", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc:"Cecil Perdium, the Mercenary King, was killed in battle before he could avenge his family. Suddenly waking up as his teenage self, Cecil must work to both overcome his poor reputation and build up his strength to save his family. Can Cecil become the mighty warrior he once was and avert his family's fate?", 
    lastRead: "2025-09-11", 
    status: "Ongoing", 
    rating: "Mid", 
    chapter: "Chapter 4",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 9, 
    type: "manhwa", 
    imageUrl: "/pictures/image4.png", 
    title: "The Knight Who Only Lives Today", 
    altTitle: "Eternally Regressing Knight",
    desc:"Is dying repeatedly a blessing? Enkrid's life-long dream of becoming a knight looked to be forever out of reach, until one day he died... and woke up at the beginning of that same day! Now that he has unlimited chances to train and engage in mortal combat, just how far can he go?", 
    lastRead: "2025-9-21", 
    status: "Completed", 
    rating: "Mid", 
    chapter: "Chapter 8",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 10, 
    type: "manhua", 
    imageUrl: "/pictures/image2.png", 
    title: "The Regressed Mercenary Has a Plan", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc:"Cecil Perdium, the Mercenary King, was killed in battle before he could avenge his family. Suddenly waking up as his teenage self, Cecil must work to both overcome his poor reputation and build up his strength to save his family. Can Cecil become the mighty warrior he once was and avert his family's fate?", 
    lastRead: "2025-09-22", 
    status: "Ongoing", 
    rating: "Good", 
    chapter: "Chapter 4",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 11, 
    type: "manhwa", 
    imageUrl: "/pictures/image3.png", 
    title: "The Knight Who Only Lives Today", 
    altTitle: "Eternally Regressing Knight",
    desc:"Is dying repeatedly a blessing? Enkrid's life-long dream of becoming a knight looked to be forever out of reach, until one day he died... and woke up at the beginning of that same day! Now that he has unlimited chances to train and engage in mortal combat, just how far can he go?", 
    lastRead: "2025-09-23", 
    status: "Ongoing", 
    rating: "Bad", 
    chapter: "Chapter 8",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
  { 
    id: 12, 
    type: "manga", 
    imageUrl: "/pictures/image4.png", 
    title: "A Regressor's Tale of Cultivation", 
    altTitle: "회귀수선전",
    desc:"It's a Korean take on the Chinese Xianxia genre. MC and his work colleagues suddenly get dropped into a world of Immortal Cultivation while on a company picnic. Every one of his colleagues have a special talent or ability except the MC, and the MC has no choice but to live as an ordinary mortal in his first life.", 
    lastRead: "2025-09-24", 
    status: "Ongoing", 
    rating: "Good", 
    chapter: "Chapter 12",
    tags: ["Action", "Fantasy", "Adventure", "Martial Arts"],
    source: ["Asura Scans"]
  },
  { 
    id: 13, 
    type: "manhua", 
    imageUrl: "/pictures/image2.png", 
    title: "The Regressed Mercenary Has a Plan", 
    altTitle: "The Regressed Mercenary's Machinations",
    desc:"Cecil Perdium, the Mercenary King, was killed in battle before he could avenge his family. Suddenly waking up as his teenage self, Cecil must work to both overcome his poor reputation and build up his strength to save his family. Can Cecil become the mighty warrior he once was and avert his family's fate?", 
    lastRead: "2025-09-25", 
    status: "Ongoing", 
    rating: "Mid", 
    chapter: "Chapter 4",
    tags: ["Action", "Fantasy", "Adventure"],
    source: ["Webtoon", "Asura Scans"]
  },
];